### ISSUE TITLE
Receiving error when attempting to preview markdown

### ISSUE THREAD

**Issue by MichaelAguilar** [dotcypress/GitHubMarkdownPreview#13]
Pressing `Ctrl + Shift + G` to preview the Markdown (or selecting that option from the menu) results in a message box displaying the following error using Sublime Text 3 on Windows 7 (64-bit):
```
Error in GitHubMarkdownPreview package:

fatal: Not a git repository (or any of the parent directories): .git
```
![image](https://cloud.githubusercontent.com/assets/6163775/4358080/5d431718-4267-11e4-9a78-5b876f340f42.png)

**Comment by shtricul** [comment]
+1 Same problem

**Comment by ahoran3** [comment]
Same problem on mac :/

**Comment by harrygfox** [comment]
+1

**Comment by okaprinarjaya** [comment]
+1 same problem

**Comment by srinath-v** [comment]
+1 same problem on linux

**Comment by Frikki** [comment]
Well, this project seems abandoned.

**Comment by thetypebeast** [comment]
+1 Same on mac...
