### ISSUE TITLE
Throws an exception when there's no internet connection.

### ISSUE THREAD

**Issue by tedmiston** [dotcypress/GitHubMarkdownPreview#17]
Error in GitHubMarkdownPreview package:

```
<urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by dotcypress** [comment]
Plugin uses GitHub and can't work without internet connection

**Comment by tedmiston** [comment]
Even with that, it could catch the exception and fail with a user friendly error message rather than expose the exception.  I can send a PR if there's interest.

**Comment by dotcypress** [comment]
PR will be awesome ;)
