### ISSUE TITLE
Strips out GitHub emoji

### ISSUE THREAD

**Issue by tedmiston** [dotcypress/GitHubMarkdownPreview#18]
For example: `:star:` &rarr; :star: in GHFM, but the plugin strips them out of the preview.

Reference: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by pjscopeland** [comment]
On the subject of character sets, it doesn't seem to do UTF-8 either.

E.g.

File                   | Github | Preview
-----------------------|--------|--------
`kwʌɪə`                | kwʌɪə  | kwÊŒÉªÉ™
`kw&#652;&#618;&#601;` | kwʌɪə  | kwÊŒÉªÉ™

**Comment by dotcypress** [comment]
Can't reproduce on last version.
