### ISSUE TITLE
WinError 2 when trying to use preview

### ISSUE THREAD

**Issue by mdw7326** [dotcypress/GitHubMarkdownPreview#19]
Just installed GitHubMarkdownPreview using PackageControl on Sublime Text 3 on Windows 10.

On first use I hit <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd> and get the following error:
![screenshot 2015-08-28 11 16 36](https://cloud.githubusercontent.com/assets/4491428/9549876/41747e3a-4d76-11e5-9a4b-f1e5d620b63b.png)

**Comment by dopry** [comment]
I get the same on windows 8. will try to debug.

**Comment by christakahashi** [comment]
I get a similar error with ST3 build 3083 on Win 10
![image](https://cloud.githubusercontent.com/assets/1870494/12046138/4f15ede8-ae66-11e5-863c-0357260f682a.png)

**Comment by jonand** [comment]
Same with ST3 3083 on Win 7.

![image](https://cloud.githubusercontent.com/assets/956526/12638512/09d9be68-c59e-11e5-8117-4cee7640d526.png)

**Comment by leegee** [comment]
I'm getting similar:
```
Error in GitHubMarkdownPreview package:

[WinError 2] The system cannot find the file specified
```

This is Windows 10 (sadly).
