### ISSUE TITLE
Unknown (blank) error on mac

### ISSUE THREAD

**Issue by flakessp** [dotcypress/GitHubMarkdownPreview#26]
After pressing ``` ctrl + shift + g ``` on ```.md``` file i'm getting the following message:
<img width="532" alt="screen shot 2016-02-03 at 17 48 49" src="https://cloud.githubusercontent.com/assets/4150771/12785650/80b7d6c8-ca9e-11e5-954c-8942ddda4f50.png">

**Comment by BenMorganIO** [comment]
Same

**Comment by dotcypress** [comment]
@flakessp could you send me ST console logs?
