### ISSUE TITLE
WinError6

### ISSUE THREAD

**Issue by whitelycorisradiata** [dotcypress/GitHubMarkdownPreview#28]
Just installed GitHubMarkdownPreview using PackageControl on Sublime Text 3 on Windows7.
![cap](https://cloud.githubusercontent.com/assets/17016982/13516197/5d81e710-e1fb-11e5-9cd6-5d4057799d22.png)

**Comment by leegee** [comment]
I'm getting that, but it is in English, and reads:
```
Error in GitHubMarkdownPreview package:

[WinError 2] The system cannot find the file specified
```

This is Windows 10 (sadly).
