### ISSUE TITLE
Add meta Content-type header with encoding to output HTML

### ISSUE THREAD

**Issue by vkotovv** [dotcypress/GitHubMarkdownPreview#31]
I've tried to use plugin to display Markdown file with cyrillic chars in it (UTF-8 file).
This is [original md file](https://gist.github.com/vkotovv/7d7858b5ecef350271f4c551c67b7224#file-original-md).
This is [resulting HTML](https://gist.github.com/vkotovv/7d7858b5ecef350271f4c551c67b7224#file-tmp_vqzvl-html).
This is what I got in Firefox 44.0 -- 
![selection_115](https://cloud.githubusercontent.com/assets/1636249/18472944/eaad0c50-79c2-11e6-9e7c-089436cb01fc.png)

This is what I expected -- 
![selection_114](https://cloud.githubusercontent.com/assets/1636249/18472953/f2a944f0-79c2-11e6-8959-d5637db9569d.png)

So I saw there is no meta tag in the resulting HTML, so I think you should add it, otherwise Firefox renders it as ISO-8859-2 document by default. [Here](https://gist.github.com/vkotovv/7d7858b5ecef350271f4c551c67b7224#file-tmp_vqzvl_fixed-html) is what it should look like.

**Comment by dotcypress** [comment]
Hey,

this plugin use GitHub api for preview, and i don't have any chance to fix it.

**Comment by vkotovv** [comment]
But here is where HTML head tag is generated: https://github.com/dotcypress/GitHubMarkdownPreview/blob/master/GHMarkdownPreview.py#L74. You can just insert this meta header there. Should I prepare a PR?
